### ISSUE TITLE
Main directory

### ISSUE THREAD

**Issue by michass** [linuxserver/docker-domoticz#34] opened 2019-01-19 06:10 UTC
Hi,
This is no issue, I'm new in docker.
I have Synology DS218+ with your container.
I want to have acces to main directory of domoticz, exactly to www folder.
How to set volumes, to expose www like config to my destination directory?
Best Regards
Michał

**Comment by tobbenb** [comment] 2019-01-19 14:34
If you volume map the www folder, everything inside will not be available anymore and that will probably make domoticz not work as intended.
You can map files or folders that does not exist inside the www folder though. 
Why do you need access to the www folder?

**Comment by michass** [comment] 2019-01-20 12:56
It can be, when container is stopped. I want use machinon theme.
https://github.com/EdddieN/machinon-domoticz_theme

**Comment by michass** [comment] 2019-01-20 15:35
I have also problem with http request from external unit to domoticz via JSON API

**Comment by tobbenb** [comment] 2019-01-20 16:23
For info about basic stuff like volume mapping, have a look at our docs section [https://www.linuxserver.io/docs](https://www.linuxserver.io/docs)

I don't understand what you mean with: It can be, when container is stopped.

You can clone the machinon to a folder on the host, then volume map the machinon folder to /var/lib/domoticz/www/styles/machinon and volume map the Settings.html to /var/lib/domoticz/www/templates/Settings.html

You need to be much more detailed about your http request issue.

**Comment by michass** [comment] 2019-01-20 18:23
Thanks,
HTTP request changed to MQTT, now works.
Thanks!
Directory and settings file mapped!
acc.to HTTP request, some requests(i have few) works, when i have "use same network" but not all
I want to use other port for domoticz, and I have uncheck this.

**Comment by tobbenb** [comment] 2019-01-23 13:52
So we can now close this?

**Comment by michass** [comment] 2019-01-23 15:59
Yes

**Closed as completed** 2019-01-24 06:39 UTC
