### ISSUE TITLE
New versioning scheme, latest on docker hub is outdated

### ISSUE THREAD

**Issue by hrak** [linuxserver/docker-domoticz#82] opened 2020-05-22 08:59 UTC
The current latest image seems outdated (V4.11786), the latest version is 2020.2 (April 26th 2020)

FYI Domoticz has adopted a new versioning scheme, see https://www.domoticz.com/wiki/Domoticz_versions_-_Commits

## Expected Behavior
Get the latest released version

## Current Behavior
get V4.11786

## Steps to Reproduce
docker pull linuxserver/domoticz:arm32v7-latest

## Environment
**OS:**      Raspbian 10
**CPU architecture:** arm32
**How docker service was installed:**      get-docker.sh

**Comment by tobbenb** [comment] 2020-05-22 18:27
We do know that it's not building new version, but the issue is out of our hands.
1. Domoticz is  not building on alpine anymore.
2. Rebase to ubuntu bionic and using domoticz binaries doesn't work for arm as domoticz use the latest debian to build the binaries and the glibc there is higher than in ubuntu bionic. Bionic is a LTS release, but domoticz doesn't give a flying fuck about that.
3. Focal is  not working for both 32 and 64 bit arm as there is a bug in docker that prevents building the base image. When docker gets their finger out of the dark place, we can finally push a new version.

**Comment by max3163** [comment] 2020-05-30 07:36
And is it possible to build an image for x86 user if arm still not working ? 

Possible to have link about the issue because I can't understand how ubuntu can't fix arm image on docker?

**Comment by tobbenb** [comment] 2020-05-30 09:54
We can't just build an x86 as our pipeline is multi-arch.
Seems it's different things that needs fixing.
https://github.com/moby/moby/issues/40734
https://github.com/docker/containerd-packaging/pull/151

**Comment by hugo-leij** [comment] 2020-06-29 18:52
Is there already an update by chance? I see reactions in both tickets, but I have to admit that these are to technical for me

**Comment by max3163** [comment] 2020-07-17 07:42
Any news about the avalaibilty of a new version  ?

**Comment by hrak** [comment] 2020-07-17 08:38
> We can't just build an x86 as our pipeline is multi-arch.
> Seems it's different things that needs fixing.
> [moby/moby#40734](https://github.com/moby/moby/issues/40734)
> [docker/containerd-packaging#151](https://github.com/docker/containerd-packaging/pull/151)

It looks like there was some activity in these issues. Ubuntu has released an update for the libseccomp package and with docker 19.03.11+ its supposed to work.

**Comment by tobbenb** [comment] 2020-07-17 13:46
Yes, I think it should work now, but I haven't checked if we started building focal again. It's vacation time, so have been busy wit other stuff. I'll check and see if it's building.

**Comment by max3163** [comment] 2020-08-17 11:20
Other issues on the build ?

**Comment by csigabit** [comment] 2020-08-17 11:57
-the baseimage is fine, it needs an update to 3.12 though, I've changed the version number only.
-minimum cmake version 3.17.0, with apk You get only 3.14.0, so I added a source build in my version.
-docker-domoticz/root/etc/services.d/domoticz/run I had to add -v after setcap.
I can say theese are not really issues, and it would be nice to see the long waited update on this container, as it has 10M+ pulls, we are not the only ones waiting. And I couldn't wait anymore, so I made a fork. [MyFork](https://hub.docker.com/r/csigabit/domoticz)
Removed telldus, openzwave, broadlink. Added ESP8266 Milight Hub, Yamaha AV Reciever, zigbee2mqtt. To prevent issues in the future with upgrades you have to go with the stable releases, because the dev branch .db not always works with the release version of domoticz.

**Comment by max3163** [comment] 2020-08-31 11:47
Hi, 

Still no official image from linuxserver ?

**Comment by tobbenb** [comment] 2020-08-31 21:07
Unfortunately not. I haven't had the time outside my normal life to look at it and also docker have been slow to fix the issues with focal. It should be fixed for users on recent OS, so I'll try to squeeze it in my schedule in the next weeks.

**Comment by max3163** [comment] 2020-09-18 14:10
Still no time on this issue ? May be someone else can find a solution ? I don't know what we need now to generate a new image but if I can help ...

**Comment by brambaars** [comment] 2020-10-02 06:39
I would really like to see an update as well. Thanks for the great work, hope you can squeeze it in, somwhere!

**Comment by tobbenb** [comment] 2020-10-03 18:41
You can try the tag below if you want to help testing. You do have to make sure your libseccomp is up to date or else you might have issues on arm devices. You need at least version 2.4.3 of libseccomp.
`lsiodev/domoticz:stable`

Be sure to make a backup of your /config folder before testing.
Also, there might be packages missing as I rebased it from alpine to ubuntu.

**Comment by hugo-leij** [comment] 2020-10-05 18:07
Thank you @tobbenb 

Unfortunately it is not running successfully, any idea what it could be?

Dockerfile:
```
version: "2.1"
services:
  domoticz:
    container_name: domoticz2020
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    image: lsiodev/domoticz:arm32v7-latest
    ports:
      - "9191:8080"
      - "6144:6144"
      - "1443:1443"
    restart: unless-stopped
    volumes:
      - "/home/pi/domoticz2020/config:/config"
```

Log:
```
domoticz2020 | [cont-init.d] 30-config: exited 0.
domoticz2020 | [cont-init.d] 99-custom-scripts: executing...
domoticz2020 | [custom-init] no custom files found exiting...
domoticz2020 | [cont-init.d] 99-custom-scripts: exited 0.
domoticz2020 | [cont-init.d] done.
domoticz2020 | [services.d] starting services
domoticz2020 | [services.d] done.
domoticz2020 | 2033-02-12 22:10:15.000  Status: Domoticz V2020.2 (c)2012-2020 GizMoCuz
domoticz2020 | 2033-02-12 22:10:15.000  Status: Build Hash: b63341bc0, Date: 2020-04-26 13:47:55
domoticz2020 | 2033-02-12 22:10:15.000  Status: Startup Path: /usr/share/domoticz/
domoticz2020 | 2033-02-12 22:10:15.000  BuildManifest: Created directory /config/plugins/
domoticz2020 | Fatal Python error: pyinit_main: can't initialize time
domoticz2020 | Python runtime state: core initialized
domoticz2020 | PermissionError: [Errno 1] Operation not permitted
domoticz2020 |
domoticz2020 | Current thread 0x7608e010 (most recent call first):
domoticz2020 | <no Python frame>
```

**Comment by j0nnymoe** [comment] 2020-10-05 18:20
@hugo-leij did you check you had the latest libseccomp installed as per @tobbenb comment?

**Comment by hugo-leij** [comment] 2020-10-05 18:47
@j0nnymoe no not yet, i'm figuring out how to update that

**Comment by tobbenb** [comment] 2020-10-06 04:53
You have to enable the backport repo somehow, if it's not active.

**Comment by DAVIZINH0** [comment] 2020-10-10 22:35
hello. i use synology docker and create a new container with the lsiodev/domoticz:stable ussing all my config of last linuxserver version.
Works fine!!!! thanks!

only one more question, its posible obtain the betas? or this only works with stables?

EDIT: in the other container i use "apk add" to install some libreries that i need in my domoticz system. In the lsiodev, the "apk add" not works :-( any solution?
thanks!

EDIT2: i used "apt-get install" instead "apk add" and works

**Comment by djedje72** [comment] 2020-11-15 07:01
@tobbenb Lsiodev/domoticz:stable works well (on Synology Docker).
Was previously with latest from this repo.
Is it possible to use latest from domoticz develop with any Lsiodev/domoticz:xxxx image?
Thank you 😄

**Comment by DAVIZINH0** [comment] 2020-12-06 16:57
any news about this?.
the lsiodev version works fine for me. but its a old stable version :-(

**Comment by yllekz** [comment] 2020-12-20 18:46
Also checking in on this. Just pulled down a fresh container on my Pi using "latest" and I immediately get "A new version of Domoticz is Available! Version: 11995"

**Comment by tobbenb** [comment] 2020-12-24 13:02
I had to redo the PR's as there have been too many changes in our pipeline since I opened them, and it was easier than resolving the conflicts manually. 
I just got my server running again, so hopefully it's merged soon.

**Comment by tobbenb** [comment] 2020-12-26 15:21
Closing this as the new containers based on ubuntu are merged. For now it's only the stable version and it's tagged as both latest and stable.

**Closed as completed by tobbenb** 2020-12-26 15:21 UTC
Labels: no-issue-activity

**Comment by DAVIZINH0** [comment] 2021-01-26 12:04
> 
> 
> Closing this as the new containers based on ubuntu are merged. For now it's only the stable version and it's tagged as both latest and stable.

hello.
do you think its posible that the "latest" will use the domoticz beta?.
it will be very interesting for advanced users, because domoticz update de stable little times at year.

thanks

**Comment by tobbenb** [comment] 2021-01-26 12:21
Latest will not be the development version as it should be a clear decision by the user to use a development build.

I'm also not sure sure if there is a good way to find out when they push new beta releases. If I remember correctly, they don't tag beta releases on github.

**Comment by DAVIZINH0** [comment] 2021-01-26 12:30
> 
> 
> Latest will not be the development version as it should be a clear decision by the user to use a development build.
> 
> I'm also not sure sure if there is a good way to find out when they push new beta releases. If I remember correctly, they don't tag beta releases on github.

sorry, development buid was correct for betas, no latest! your right!

i don´t know if domoticz use the beta tag in github i think they use the "development branch" for betas and the "master" for stables, but certenly im not sure.

Previous to this migration to a ubuntu, the linuxserver container have a branch that includes the betas. I dont remenber if was the latest or development. But i was very usseful for users because the domoticz stable only updates one for year (aprox).
this is only a suggestion obviously

thanks for your fast reply!!

**Comment by tobbenb** [comment] 2021-01-26 12:51
Domoticz and releases are a mess....

Since we now use the binaries built by domoticz and there is no endpoint for us to check when they release a new beta, it doesn't make it so easy for us to set something up. 

You could try to ask them to make a pre-release as it will be much easier for us to set up a Dev branch.
